---
title: "Visualization"
subtitle: "Part 2"
author: "AJ Catalano"
date: "11/8/2021"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)
```

## Adding labels

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maximum Daily Temperature",
    caption = "Data from R NOAA package; temperatures in 2017"
    )
```

## Scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maximum Daily Temperature",
    caption = "Data from R NOAA package; temperatures in 2017"
    ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) +
  scale_y_continuous(
    trans = "log",
    position = "right"
  )
```

#### Color scales

```{r}
# playing with color hue and using scale_color_hue to rename key

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maximum Daily Temperature",
    caption = "Data from R NOAA package; temperatures in 2017"
    ) + 
  scale_color_hue(h = c(100, 200),
                  name = "Location")

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maximum Daily Temperature",
    caption = "Data from R NOAA package; temperatures in 2017"
    ) + 
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)
```

## Themes

Moving the legend:

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maximum Daily Temperature",
    caption = "Data from R NOAA package; temperatures in 2017"
    ) + 
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) + 
  theme(legend.position = "bottom")
```

Changing overall theme:

```{r}
# notice how theme(legend.position = "bottom") is ignored:

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maximum Daily Temperature",
    caption = "Data from R NOAA package; temperatures in 2017"
    ) + 
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) + 
  theme(legend.position = "bottom") + 
  ggthemes::theme_few()

# now it's not ignored

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maximum Daily Temperature",
    caption = "Data from R NOAA package; temperatures in 2017"
    ) + 
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```

## Setting options

```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = .6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data arguments in `geom`

```{r}
central_park = 
  weather_df %>%
  filter(name == "CentralPark_NY")

waikiki =
  weather_df %>% 
  filter(name == "Waikiki_HA")

# two geometries that apply to separate datasets

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)
```

